### ISSUE TITLE
Is this working when the app is killed?

### ISSUE THREAD

**Issue by naufanituharish** [stumbleapp/react-native-app-utils#1]
Hi there,

Is this package working when the app is in killed state?
I just try it from background state, and it's working well,..
But when the app is in killed state, when i do kill the app it's not working,.. 

regards,

**Comment by 8BallBomBom** [comment]
From what we've tested and currently use with Firebase Notifications our app does start even after being killed.
Pretty much tied in with the background service that tends to survive the app being killed.
Then again we haven't tested with a range of devices/android versions.

Can you provide more info as to how you are executing the startApp function and on which device/android version?

**Comment by naufanituharish** [comment]
Hi,

currently we are developing voip App using Voximplant SDK, It using FCM push notification to inform the device that there's incoming call from other user, we are using react native 0.62.2 and react native firebase v8.0.0, it working well when we do minimize the app by tapping home, but when the app is closed by swiping in the ui, i meant quite/ killed state, the app won't launch,.

based on the react native firebase documentation we do follow the instruction to handle background push notification like this:

in the root index.js we handle the firebase notification,.

```
import {AppRegistry, Platform} from 'react-native';
import messaging from '@react-native-firebase/messaging';
import Main from './src/index';
import PushBackground from './src/services/PushBackground';
import {name as appName} from './app.json';

if (Platform.OS === 'android') {
    messaging().setBackgroundMessageHandler(remoteMessage => PushBackground(remoteMessage));
}

AppRegistry.registerComponent(appName, () => Main);
```
and do handle the incoming notification in the pushbackground function, inside the function we do call the Utils.startApp()

we do test on device samsung galaxy A8 2018

regards,

**Comment by naufanituharish** [comment]
Hi @8BallBomBom ,
there's our mistake,, we did wrong handle in the main application,,. 
it works like a charm,.. thank you.

**Comment by 8BallBomBom** [comment]
@naufanituharish Glad to hear everything is working as expected.

We could definitely expand on the docs to better explain things in future.
Like for example the startApp function tends to work mostly in a background service function.
Do you have any requests and would you like to expand on what the issue was and how you fixed it?

**Comment by naufanituharish** [comment]
@8BallBomBom as i do mention before, we also use voximplant SDK, when the push notification receive it will be invoking voximplant SDK function to tell the server that the notification were received and and the sdk will listen to the message that will invoke incoming call,. And i do not well handle the listener event so the app wont launch,, and the silly things i do not check the log before posting the issue,.. 😄

**Comment by 8BallBomBom** [comment]
ahaha no worries :+1:

**Comment by naufanituharish** [comment]
Hi, @8BallBomBom i would ask other question,. the application run but the device keep locked,. means that the users do need to unlock device first to see incoming call screen,.. do you have any suggestion for my issue?? to make the app launch above the lock screen??

**Comment by 8BallBomBom** [comment]
The screen wake lock function has some flags that should allow showing the app over the lock screen but they currently only apply to Android 8 and below due to deprecation.
Anything above should run this `activity.setShowWhenLocked( true );`
But that seems to be ineffective in most cases.
Have you tried calling `Utils.aquireScreenLock();` after starting the app?

We will be looking into this to see if we can implement a fix for this as Android versions and devices have different results.
Until then, have you tried [this](https://github.com/react-native-webrtc/react-native-callkeep) module?
Might let you interface with the standard calling mechanisms to get a result.

**Comment by naufanituharish** [comment]
Thank you for the assistance, we have try `Utils.aquireScreenLock()` but not working, might be we will use full screen intent to show the notification and let users to press it to open the app,. and for the react-native-callkeep, we use it for the ios,. but we thought we want something different with android because we have more users in android,. 😄

**Comment by 8BallBomBom** [comment]
I will see if theres anything that can be done.
There is functionality to dismiss the keyguard which would then allow the app to appear and after that it would put the keyguard back. Just never really looked into hooking it up :smiley: 
Only issue with that though is i don't think it works if you have a pin/pattern.
